cmake_minimum_required(VERSION 3.18)
project(FFmpegTests C)
enable_testing()
if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64|ARM64)$")
    set(ARCHITECTURE arm64)
else()
    set(ARCHITECTURE x86_64)
endif()
add_subdirectory(.. ffmpeg)
add_executable(codec_test codec_test.c)
target_link_libraries(codec_test PRIVATE ffmpeg)
add_test(NAME codecs COMMAND codec_test)
add_test(NAME vp9_opus COMMAND codec_test "${CMAKE_CURRENT_SOURCE_DIR}/vp9-opus.webm")
add_test(NAME vp8_vorbis COMMAND codec_test "${CMAKE_CURRENT_SOURCE_DIR}/vp8-vorbis.webm")
